### PR TITLE
add font support

### PR DESCRIPTION
**Pull request by jedahan**
from https://cgit.freedesktop.org/fontconfig/commit/?id=8c255fb

### CODE REVIEW

**Comment by sunhasgothishaton** [comment]
Isn't this already fixed? Ubuntu 18.04 stores my fonts in ~/.local/sharer/fonts

**Comment by jedahan** [comment]
so yeah, some of these PRs are 'unnecessary' in the sense if its your first time opening the latest version of the software, it will be in XDG dirs.

however I also like that antidot can migrate my settings from the time before they supported it. I found a lot of stuff that only needed a move.

**Comment by sunhasgothishaton** [comment]
Yes, I see now. I didn't think about that. That would be good to support

**Comment by doron-cohen** [comment]
Notice that antidot will not migrate if the target file already exist. This is to avoid running over newer version configuration. In this case the old config file will remain in the home dir.

**Comment by telans** [comment]
> Notice that antidot will not migrate if the target file already exist. This is to avoid running over newer version configuration. In this case the old config file will remain in the home dir.

Does it display a message about this? That could be a good thing to mention

**Comment by doron-cohen** [comment]
It does

**Pull request merged**
